environment      = "Development"
rg_name          = "test-rg"
location         = "Central India"
owner            = "Mukesh Verma"
address_space    = ["10.0.0.0/16"]
address_prefixes = ["10.0.0.0/24"]
public_ip_name   = "public-ip"
nic_name         = "vm-nic"
vm_name          = "vm01"
sku              = "Standard_B1s"
admin_username   = "testuser"
nsg_name         = "vm-nsg"
